add permission deploy github pages

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -4,6 +4,11 @@ on:
   workflow_call:
   workflow_dispatch:
 
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+  
 jobs:
   e2e-test:
     name: Run E2E Tests
@@ -81,26 +86,29 @@ jobs:
         with:
           path: 'e2e/reports/cucumber-html-report.html'
           name: pages
-
-  deploy-report:
-    name: Deploy E2E Report to GitHub Pages
-    runs-on: ubuntu-latest
-    needs: e2e-test
-    steps:
-      - name: Download report artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: pages
-
-      - name: List contents of publish directory for debugging
-        run: ls -la ./ || echo "Directory not found"
-
       - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./cucumber-html-report.html
+        id: deployment
+        uses: actions/deploy-pages@v4
 
-      - name: Print GitHub Pages URL
-        run: |
-          echo "GitHub Pages deployed at: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/index.html"
+  # deploy-report:
+  #   name: Deploy E2E Report to GitHub Pages
+  #   runs-on: ubuntu-latest
+  #   needs: e2e-test
+  #   steps:
+  #     - name: Download report artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: pages
+
+  #     - name: List contents of publish directory for debugging
+  #       run: ls -la ./ || echo "Directory not found"
+
+  #     - name: Deploy to GitHub Pages
+  #       uses: peaceiris/actions-gh-pages@v3
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         publish_dir: ./cucumber-html-report.html
+
+  #     - name: Print GitHub Pages URL
+  #       run: |
+  #         echo "GitHub Pages deployed at: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/index.html"
